services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    env_file:
      - ./Frontend/.env
    volumes:
      - ./Frontend:/app
      - /app/node_modules   # Prevent override!
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "5050:5000"
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
      - /app/node_modules   # Prevent override!
    command: npm run dev
