version: "4.9"

services:
  backend:
    ports:
      - "8080:8080"
    volumes:
      - ./Backend:/app/Backend
      - backend_node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
    command: npm run dev

  frontend:
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app/Frontend
      - frontend_node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
    command: npm run dev

volumes:
  frontend_node_modules:
  backend_node_modules:
