services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: it299-backend
    env_file:
      - ./Backend/.env
    working_dir: /app  # matches where dist is copied
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - it299

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: it299-frontend
    environment:
      - VITE_API_URL=http://localhost:8080
    working_dir: /app  # matches where dist is copied
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - it299

networks:
  it299:
