services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
      - backend_node_modules:/app/node_modules
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./Frontend/.env
    volumes:
      - ./Frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev
    depends_on:
      - backend

volumes:
  frontend_node_modules:
  backend_node_modules:
