name: ⚙️ CI & Semantic Release

on:
  workflow_call:
    inputs:
      run_backend:
        required: true
        type: boolean
      run_frontend:
        required: true
        type: boolean

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: [backend, frontend]

    # ✅ Skip matrix jobs based on input flags
    if: |
      (matrix.workspace == 'backend' && inputs.run_backend) ||
      (matrix.workspace == 'frontend' && inputs.run_frontend)

    defaults:
      run:
        working-directory: ${{ matrix.workspace == 'backend' && 'Backend' || 'Frontend' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npx tsc --noEmit

      - name: Placeholder Test
        run: echo "✅ Tests passed"

  release:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    needs: matrix
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      semver_tag: ${{ steps.semver.outputs.new_release_version }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      - name: Run semantic-release
        id: semver
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save version
        run: echo "${{ steps.semver.outputs.new_release_version }}" > semver_tag.txt

      - name: Save CI metadata
        run: |
          echo '{ "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'", "branch": "${{ github.ref_name }}" }' > ci-meta.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-meta
          path: |
            semver_tag.txt
            ci-meta.json
