name: ⚙️ CI & Semantic Release

on:
  workflow_call:
    inputs:
      run_backend:
        required: true
        type: boolean
      run_frontend:
        required: true
        type: boolean
      is_pr:
        required: false
        type: boolean

jobs:
  backend:
    if: ${{ inputs.run_backend }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci
        working-directory: .

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npx tsc --noEmit

      - name: Placeholder Test
        run: echo "✅ Backend tests passed"

  frontend:
    if: ${{ inputs.run_frontend }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci
        working-directory: .

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npx tsc --noEmit

      - name: Placeholder Test
        run: echo "✅ Frontend tests passed"

  release:
    if: ${{ !inputs.is_pr && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test') }}
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      semver_tag: ${{ steps.semver.outputs.new_release_version }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      - name: Run semantic-release
        id: semver
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save version
        run: echo "${{ steps.semver.outputs.new_release_version }}" > semver_tag.txt

      - name: Save CI metadata
        run: |
          echo '{ "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'", "branch": "${{ github.ref_name }}" }' > ci-meta.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-meta
          path: |
            semver_tag.txt
            ci-meta.json

      - name: Set tag as output
        id: set_tag
        run: |
          TAG=$(cat semver_tag.txt 2>/dev/null || echo "latest")
          echo "tag=$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
