name: 🧠 Orchestrator Pipeline

on:
  push:
    branches: [main, test, dev, feature/**]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      run_ci: ${{ steps.commit_check.outputs.run_ci }}
    steps:
      - uses: actions/checkout@v4

      - name: Paths Filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'Backend/**'
            frontend:
              - 'Frontend/**'

      - name: Check for [run ci] in commit message
        id: commit_check
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Last commit: $COMMIT_MSG"
          if echo "$COMMIT_MSG" | grep -iq '\[run ci\]'; then
            echo "run_ci=true" >> $GITHUB_OUTPUT
          else
            echo "run_ci=false" >> $GITHUB_OUTPUT

  trigger-ci:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' || needs.changes.outputs.frontend == 'true' || needs.changes.outputs.run_ci == 'true' }}
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      run_backend: ${{ needs.changes.outputs.backend == 'true' }}
      run_frontend: ${{ needs.changes.outputs.frontend == 'true' }}
      is_pr: ${{ github.event_name == 'pull_request' }}

  build-publish:
    needs: trigger-ci
    uses: ./.github/workflows/build-publish.yml
    secrets: inherit
    with:
      tag: ${{ needs.trigger-ci.outputs.semver_tag }}
      is_pr: ${{ github.event_name == 'pull_request' }}
      run_backend: ${{ needs.changes.outputs.backend == 'true' }}
      run_frontend: ${{ needs.changes.outputs.frontend == 'true' }}
