name: 🧠 Orchestrator Pipeline

on:
  push:
    branches:
      - main
      - test
      - dev
      - feature/**
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4

      - name: Paths Filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'Backend/**'
            frontend:
              - 'Frontend/**'

  trigger-ci:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' || needs.changes.outputs.frontend == 'true' }}
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      run_backend: ${{ needs.changes.outputs.backend == 'true' }}
      run_frontend: ${{ needs.changes.outputs.frontend == 'true' }}
      is_pr: ${{ github.event_name == 'pull_request' }}
